version: "3.9"

services:
  go_db:
    image: postgres:12
    container_name: go_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "1234"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data
    
volumes:
  pgdata: {}